services:
  app:
    image: argon-dev22/app:v0.0.0
    build: 
      context: .
      target: dev
      secrets:
        - app-secret
    ports:
      - "5432:5432"
    command: ["sleep", "infinity"]
    volumes:
      - ./app:/app
      - app-volume:/mnt
    environment:
      - ENV=dev
      - DEBUG=${DEBUG:-True}

volumes:
  app-volume:
  
secrets:
  app-secret:
    environment: APP_SECRET
    file: ./app_secret.txt
